### ISSUE TITLE
The whole interface is assuming Docker container

### ISSUE THREAD

**Issue by HealthyPear** [HealthyPear/protopipe-grid-interface#38]
in case of Linux users the CTADIRAC framework is installed natively and there is no need to keep both source and output folder in the $HOME.

Also for singularity containers the home is shared and it is not obvious that the users puts (or links) everything there

the script has to at least differentiate between source code path and output path

also the "shared_folder" name for the output directory makes sense only in case of a container of some kind...

**Comment by kosack** [comment]
Perhaps there is no reason to support bare linux, if docker is sufficient.  Given how little manpower we have, simpler is better

**Comment by HealthyPear** [comment]
Docker needs to be installed and e.g. on the in2p3 machine I don't have it, so you would need to ask for an admin to do it whereas is more simple to fix this in a way that the interface allows for 2 arguments (which I am making defaulting to home) one for where the user has put the source code and one where to put the folder which contains analysis and productions
