### ISSUE TITLE
Unable to create conda env on MAC

### ISSUE THREAD

**Issue by Iburelli** [HealthyPear/protopipe-grid-interface#76]
**Describe the bug**
Hi!
when trying to create protopipe-CTADIRAC env on the MacBook of one of our students we get the following error:

ResolvePackageNotFound: 
  - diracgrid::fts3

We tried both dev and release environments (following the instructions from protopipe documentation) but we always get the same error. 
We tried to delete and re-create env, after updating conda but we still get the error. Any Idea on how to proceed?

**Desktop (please complete the following information):**
 - OS: MacBook

**Comment by kosack** [comment]
It worked for me on a macbook.   I see the fts3 package both in the *diracgrid* and *conda-forge* channels.  But perhaps there is a restriction on the version of python? What version are you using?  I installed with 3.8
```
% anaconda search fts3 

Using Anaconda API: https://api.anaconda.org
Packages:
     Name                      |  Version | Package Types   | Platforms       | Builds
     ------------------------- |   ------ | --------------- | --------------- | ----------
     conda-forge/fts3          |   3.12.0 | conda           | noarch          | pyhd8ed1ab_0
                                          : File Transfer Service REST API
     diracgrid/fts3            |          | conda           | noarch          | py_0
                                          : FTS Python 3 CLI and libraries
Found 2 packages
```

**Comment by HealthyPear** [comment]
Hi @Iburelli,

I guess my last instruction didn't work...thanks for opening the issue.

To be clearer: you get this error just when doing e.g. `conda env create -f environment_development.yml`, right?
Even before installing protopipe and the interface?

I could never reproduce this issue on my macos, and I also checked that it works on a `Ubuntu 20.04.4 LTS` with `conda 4.13.0`...

If you wish we can have a zoom meeting in the next days to check this face-to-face.

@kosack : Python 3.8 is the only supported version in both environments due to upgrade breaking changes with CTADIRAC when using more than that (but this was sometime ago)

**Comment by Iburelli** [comment]
Hi!
@HealthyPear yes  the probem shows up when trying `conda env create -f environment_development.yml ` , before installing protopipe.
 We followed your instructions (thanks again) but we did not succeed. Meanwhile I had to change my pc an trying to install the environment on ubuntu 22 I get the same error. Just to make sure it was not just me I also tried on farm always obtaining the same result. Both systems are updated to miniconda 4.13.0
@kosack I tried to look for the package (on my laptop)  but I get the following output: 
Loading channels: done
No match found for: fts3. Search: *fts3*

PackagesNotFoundError: The following packages are not available from current channels:

  - fts3

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

This week I'm busy with a PhD school so I have only the evenings free, after 18.30. Would it be ok for you if we meet next week?

**Comment by Iburelli** [comment]
Hi!
I managed to solve the problem in the following way: 
I first downloaded diracos and source diracosrc:

- curl -LO https://github.com/DIRACGrid/DIRACOS2/releases/latest/download/DIRACOS-Linux-x86_64.sh
- bash DIRACOS-Linux-x86_64.sh
- source diracos/diracosrc

Inside protopipe-grid-interface/environment_development.yaml:
- diracgrid::fts3 line becomes fts3 

At this point I create the environment 

- `conda env create -f protopipe-grid-interface/environment_development.yaml`

I then go back to my standard conda env 

- `conda deactivate `
- `source .bashrc`

At this point I tried to install protopipe (pip install -e ‘.[all]’ but I was obtaining some errors.
Than I modified the file protopipe/environment_developement.yml 

- name: protopipe-dev → name: protopipe-CTADIRAC-dev
-` conda env update -f protopipe/environment_development.yml`

I then activate my env and install protopipe and the interface (in both cases `pip install -e ‘.[all]’` from the appropriate directory)
I have no idea why, but it works
